language: python
#branches:
#  only:
#    - master
#    - develop
sudo: false
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  #- conda config --add channels birdhouse
  #- conda config --add channels conda-forge
  #- conda install -q "libnetcdf <4.4.0" "hdf5 >=1.8.15" "isl <0.16" zlib "udunits2 >=2.2.20" libuuid expat curl gcc
  - conda install -c birdhouse -c conda-forge qa-dkrz  # get qa-dkrz deps
  - conda remove qa-dkrz   # but skip qa-dkrz itself

  # Get build script
  - export PREFIX="$HOME/miniconda"
  - echo "CC=\"/usr/bin/gcc\"" > install_configure
  - echo "CXX=\"/usr/bin/g++\"" >> install_configure
  - echo "CFLAGS=\"-O2 -Wall\"" >> install_configure
  - echo "CXXFLAGS=\"-O2 -Wall -D NC4\"" >> install_configure
  - echo "LIB=\"${PREFIX}/lib\"" >> install_configure
  - echo "INCLUDE=\"${PREFIX}/include\"" >> install_configure

script:
  - touch .ignore_GitHub
  - ./install CF
  - ./install CORDEX
  - ./install CMIP5
after_script:
  - test -d "./bin"
  - ./scripts/qa-dkrz --example
